# Generated by Django 4.2.7 on 2025-09-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('tp_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nvarchar1', models.CharField(max_length=255, verbose_name='عنوان')),
                ('ntext2', models.TextField(verbose_name='متن')),
                ('tp_Created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('tp_Modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'db_table': 'Announcements',
            },
        ),
    ]
